import 'package:flutter/material.dart';

void main() {
  runApp(const LectureAssistantApp());
}

class LectureAssistantApp extends StatelessWidget {
  const LectureAssistantApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'مساعد المحاضرات',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(
          seedColor: Colors.deepPurple,
          brightness: Brightness.light,
        ),
        useMaterial3: true,
        fontFamily: 'Roboto', // Replace with an Arabic font if available, but Roboto works fine as fallback
      ),
      // Register routes for safety
      initialRoute: '/',
      routes: {
        '/': (context) => const HomeScreen(),
      },
      builder: (context, child) {
        return Directionality(
          textDirection: TextDirection.rtl, // RTL for Arabic
          child: child!,
        );
      },
    );
  }
}

class HomeScreen extends StatefulWidget {
  const HomeScreen({super.key});

  @override
  State<HomeScreen> createState() => _HomeScreenState();
}

class _HomeScreenState extends State<HomeScreen> {
  final TextEditingController _lectureTextController = TextEditingController();
  bool _isLoading = false;
  String? _summary;
  String? _explanation;

  void _processLecture() async {
    if (_lectureTextController.text.trim().isEmpty) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text('الرجاء إدخال نص المحاضرة أولاً')),
      );
      return;
    }

    setState(() {
      _isLoading = true;
      _summary = null;
      _explanation = null;
    });

    // Simulate API delay for AI processing
    await Future.delayed(const Duration(seconds: 2));

    setState(() {
      _isLoading = false;
      // In a real app, this would be generated by an AI API (like OpenAI)
      _summary = "هذا هو الملخص لأهم النقاط التي ذكرتها في النص. يركز الملخص على المفاهيم الأساسية والأفكار الرئيسية مع تجاهل التفاصيل غير الضرورية.";
      _explanation = "ببساطة، الفكرة هي كالتالي:\nتخيل أنك تبني منزلاً، الأساسات هي أهم شيء. هذا ما تتحدث عنه المحاضرة. إذا فهمت الأساس، سيسهل عليك فهم باقي المواضيع.\n\nخطوات الفهم المباشر:\n1. ركز على الصورة الكبرى.\n2. اربط المعلومات بأشياء تعرفها مسبقاً.\n3. لا تحفظ، بل حاول أن تفهم المنطق.";
    });
  }

  @override
  void dispose() {
    _lectureTextController.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('مساعد المحاضرات الذكي', style: TextStyle(fontWeight: FontWeight.bold)),
        centerTitle: true,
        backgroundColor: Theme.of(context).colorScheme.inversePrimary,
      ),
      body: SafeArea(
        child: SingleChildScrollView(
          padding: const EdgeInsets.all(16.0),
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.stretch,
            children: [
              const Text(
                'أدخل نص المحاضرة أو ملاحظاتك هنا:',
                style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold),
              ),
              const SizedBox(height: 12),
              TextField(
                controller: _lectureTextController,
                maxLines: 8,
                decoration: InputDecoration(
                  hintText: 'قم بلصق النص هنا لكي يتم تلخيصه وشرحه بأسلوب مبسط...',
                  border: OutlineInputBorder(
                    borderRadius: BorderRadius.circular(12),
                  ),
                  filled: true,
                  fillColor: Theme.of(context).colorScheme.surfaceContainerHighest.withOpacity(0.3),
                ),
              ),
              const SizedBox(height: 20),
              ElevatedButton.icon(
                onPressed: _isLoading ? null : _processLecture,
                icon: _isLoading 
                    ? const SizedBox(
                        width: 20, height: 20, 
                        child: CircularProgressIndicator(strokeWidth: 2)
                      )
                    : const Icon(Icons.auto_awesome),
                label: const Padding(
                  padding: EdgeInsets.symmetric(vertical: 12),
                  child: Text(
                    'لخّص واشرح لي',
                    style: TextStyle(fontSize: 18),
                  ),
                ),
                style: ElevatedButton.styleFrom(
                  shape: RoundedRectangleBorder(
                    borderRadius: BorderRadius.circular(12),
                  ),
                ),
              ),
              const SizedBox(height: 30),
              if (_summary != null && _explanation != null) ...[
                _buildResultCard(
                  title: 'الملخص الذكي',
                  content: _summary!,
                  icon: Icons.summarize,
                  color: Colors.blue,
                ),
                const SizedBox(height: 16),
                _buildResultCard(
                  title: 'الشرح المبسط (أفضل من الدكتور)',
                  content: _explanation!,
                  icon: Icons.lightbulb,
                  color: Colors.amber.shade700,
                ),
              ]
            ],
          ),
        ),
      ),
    );
  }

  Widget _buildResultCard({
    required String title,
    required String content,
    required IconData icon,
    required Color color,
  }) {
    return Card(
      elevation: 2,
      shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(16)),
      child: Padding(
        padding: const EdgeInsets.all(16.0),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Row(
              children: [
                Icon(icon, color: color, size: 28),
                const SizedBox(width: 12),
                Expanded(
                  child: Text(
                    title,
                    style: TextStyle(
                      fontSize: 20,
                      fontWeight: FontWeight.bold,
                      color: Theme.of(context).colorScheme.primary,
                    ),
                  ),
                ),
              ],
            ),
            const Divider(height: 24),
            Text(
              content,
              style: const TextStyle(
                fontSize: 16,
                height: 1.6,
              ),
            ),
          ],
        ),
      ),
    );
  }
}
